# This container serves as a pure data container
app:
  build: ../app/
  container_name: amak-app-test
  volumes:
    - //hostc/amak/amak-frontend:/var/www/amak-frontend
    - //hostc/amak/amak-cms:/var/www/amak-cms
    - //hostc/amak/amak-portal:/var/www/amak-portal
    - //hostc/amak/amak-docker/httpd/config:/config/

# Percona database
db:
  #image: amak_db_beta
  build: ../db/
  container_name: amak-db-test
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=amak


# Apache2 httpd
httpd:
  build: ../httpd/
  container_name: amak-httpd-test
  ports:
    - "80:80"
  links:
    - db
  volumes_from:
    - app:rw


# Selenium standalone
firefox1:
  build: StandaloneFirefox/
  container_name: amak-firefox1
  links:
    - httpd
  ports:
   - "4445:4444"
#  volumes:
#    - //hostc/amak/amak-docker/test/hostconfig/hosts.tst:/etc/hosts


#firefox2:
#  build: test/StandaloneFirefox/
#  container_name: amak-firefox2
#    ports:
#     - "4445:4444"
firefoxdebug:
    build: StandaloneFirefoxDebug/
    container_name: amak-firefoxdebug
    ports:
        - "5900:5900"
        - "4444:4444"
  #  volumes:
  #      - //hostc/amak/amak-docker/test/hostconfig/hosts.tst:/etc/hosts
     

chrome1:
  build: StandaloneChrome/
 #   container_name: amak-chrome1
 #   ports:
 #     - "3333:3333"

#chrome2:
 # build: test/StandaloneChrome/
  #container_name: amak-chrome1
#  ports:
#    - "3334:3333"