# Selenium standalone

firefoxdebug:
    build: StandaloneFirefoxDebug/
    container_name: amak-firefoxdebug
    ports:
        - "4440:4444"
        - "4441:5900"
    restart: unless-stopped
chromedebug:
    build: StandaloneChromeDebug/
    container_name: amak-chromedebug
    ports:
        - "4442:4444"
        - "4443:5900"
    restart: unless-stopped