# Selenium standalone

firefoxdebug:
    build: StandaloneFirefoxDebug/
    container_name: amak-firefoxdebug
    ports:
        - "127.0.0.1:5900:5900"
        - "127.0.0.1:4444:4444"
    restart: always