# This container serves as a pure data container
app:
  image: ubuntu:trusty
  container_name: amak-app
  volumes:
    - ./app:/var/www
  tty: true

# Percona database
db:
  build: db/
  container_name: amak-db
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=amak

# Apache2 httpd
httpd:
  build: httpd/
  container_name: amak-httpd
  ports:
    - "80:80"
  links:
    - db
  volumes_from:
    - app:rw
